save_dir: save
name: FedAvg          # 实验名称
n_clients: 10
noniid: True          # True
dirichlet: False      # dirichlet作为 noniid_2
alpha: 1.0            # Dirichlet 分布参数
dataset_path: data    # /home/user/PycharmProjects/data/cifar
dataset: FashionMNIST      # Cifar10  # FashionMNIST
classes: 10
batch_size: 64
lr:  0.001
round: 100
local_epoch: 1        # 5  1

resume: False
overwrite: True
